name: Lint

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  pull-requests: write

jobs:
  run-linters:
    name: Run linters
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Set up Pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 6.7.0

      - name: Install Node.js dependencies
        run: pnpm install

      - name: Run linters
        id: linters
        uses: wearerequired/lint-action@v2
        with:
          eslint: true
          prettier: true
          continue_on_error: false

  notify-on-success:
    runs-on: ubuntu-latest
    needs: run-linters
    if: ${{ success() }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Comment on success
        uses: actions/github-script@v7
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          URL: ${{ github.event.pull_request.comments_url }}
          MESSAGE: "Great news! The linters didn't find any issues with your code. Keep up the good work!"
        with:
          script: |
            curl -L \
              -X POST \
              $URL \
              -H "Authorization: Bearer $GITHUB_TOKEN
              -H "Accept: application/vnd.github+json" \
              -H "Content-Type: application/json" \
              -d '{
                "body": $MESSAGE
              }' \

  notify-on-failure:
    runs-on: ubuntu-latest
    needs: run-linters
    if: ${{ failure() }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Comment on failure
        uses: actions/github-script@v7
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          URL: ${{ github.event.pull_request.comments_url }}
          MESSAGE: "Hey there! It looks like the linters encountered some issues. To resolve them, please run the following commands in your local environment:\n\n```\npnpm lint\npnpm prettier\n```\n\nThese commands will help identify and automatically fix any code styling or formatting problems. Once you've run these commands, feel free to push your changes again. If you need further assistance, don't hesitate to ask!"
        with:
          script: |
            curl -L \
              -X POST \
              $URL \
              -H "Authorization: Bearer $GITHUB_TOKEN \
              -H "Accept: application/vnd.github+json" \
              -H "Content-Type: application/json" \
              -d '{
                "body": $MESSAGE
              }' \
